apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: development-rolebinding
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: development-role
subjects:
- kind: ServiceAccount
  name: dev
  namespace: development